### ISSUE TITLE
Build issues: multiple definition, library location

### ISSUE THREAD

**Issue by Artoria2e5** [TurboVNC/vncbenchtools#1]
It could be a good idea to make this tool a little easier to use by giving some build instructions. Right now:

### Static library locations are not documented

Honestly, is static even necessary?

Manual edit of `CMakeList.txt` and `cmakescripts/FindTurboJPEG.cmake` to my system locations makes that go away (yes, the turbo bit could be a define on my part). Could make more sense to use a less stingy find logic.

### multiple definition

With `cmake -DENCODER=turbo-h264 -DDECODER=turbo-1.0 .; make`, there's:

```
[ 25%] Linking C executable compare-encodings
/bin/ld: CMakeFiles/compare-encodings.dir/translate.c.o:(.bss+0x0): multiple definition of `rfbServerFormat'; CMakeFiles/compare-encodings.dir/misc.c.o:(.bss+0x20): first defined here
```

Manual editing of `CMakeFiles/compare-encodings.dir/link.txt` to throw in a `-Wl,--allow-multiple-definition` makes that go away, but it's a bit concerning.

* * *

(Of course getting these done does not make it just work, because... oops, dataset. I still got to send an email to you! I was mainly curious about how turbo-h264 performs and the possiblity of a turbo-jxl encoding, FWIW.)

**Comment by dcommander** [comment]
I can share a link to the datasets through e-mail.

**Comment by dcommander** [comment]
Apparently the older version of GCC I used "back in the day" to compile these tools didn't detect the multiple definition issue.  I reproduced it with GCC 10 and fixed it.
