### ISSUE TITLE
Decoding phase

### ISSUE THREAD

**Issue by nEghbal** [TurboVNC/vncbenchtools#2]
Hello,

I have a general question about all encoding methods. 
Do we need all encoded parts of an image to be able to start decoding at the client side or there are some of the encodings for which we can start decoding incrementally as different parts of the image arrive? 

Thanks,
Nooshin

**Comment by dcommander** [comment]
Answered on the tigervnc-devel list:
https://groups.google.com/g/tigervnc-devel/c/tNcp3Ig48eg/m/fi78MA8sDwAJ
